# Project information
site_name: SFH Foundation
site_description: Self, Soul, and Joyful Surrender
site_url: https://sfh-foundation.github.io/sfhfoundation/site/
site_dir: public/site

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: orange
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

extra_css: [extra.css]

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/SFH-Foundation/sfhfoundation'
    - type: 'twitter'
      link: 'https://twitter.com/cryptowanderer'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.extra

# Page tree
nav:
- Home: '../'
- Audio: 'https://sfh-foundation.github.io/sfhfoundation/'
- Newsletter: 'https://sfhfoundation.substack.com/'
- Books:
  - 'Overview': 'books/index.md'
  - General on Islam: 
      - 'Introduction': 'books/general-islam/index.md'
      - 'Transformative Worship in Islam': 'books/general-islam/transformative-worship.md'
      - 'The Thoughtful Guide to Islam': 'books/general-islam/thoughtful-guide-islam.md'
      - 'Elements of Islam': 'books/general-islam/elements-islam.md'
      - 'Sayings of the Prophet Muhammad': 'books/general-islam/sayings-muhammad.md'
      - 'Prophetic Traditions in Islam: On the Authority of the Family of the Prophet': 'books/general-islam/prophetic-traditions.md'
  - The Qur’an:
      - 'Introduction': 'books/quran/index.md'
      - 'The Story of Creation in the Qur’an': 'books/quran/story-creation-quran.md'
      - 'The Mercy of the Qur’an and The Advent of Zaman': 'books/quran/mercy-quran-advent-zaman.md'
      - 'The Heart of the Qur’an - Surat Yā Sīn': 'books/quran/heart-quran-perfect-mizan.md'
      - 'The Essential Message Of the Qur’an': 'books/quran/essential-quran.md'
      - 'Sacred Alchemy: A Collection of Qur’anic Verses': 'books/quran/sacred-alchemy.md'
      - 'Keys to the Qur’an - Volume 5 The Juz Amma': 'books/quran/keys-quran.md'
      - 'Qur’an’s Prescription for Life': 'books/quran/quran-prescriptions.md'
  - Sufism and Self-Knowledge: 
      - 'Introduction': 'books/sufism/index.md'
      - 'The Thoughtful Guide to Sufism': 'books/sufism/thoughtful-guide-sufism.md'
      - 'Elements of Sufism': 'books/sufism/elements-sufism.md'
      - 'Sufi Encounters: Sharing the Wisdom of Enlightened Sufis': 'books/sufism/sufi-encounters.md'
      - 'The Sufi Way of Self-Enfoldment': 'books/sufism/sufi-self-enfoldment.md'
      - 'Witnessing Perfection: A Sufi Guide': 'books/sufism/witnessing-perfection.md'
      - 'The Sayings & Wisdom of Imam `Ali': 'books/sufism/sayings-imam-ali.md'
      - 'The Hikam - The Wisdom of Ibn `Ata’ Allah': 'books/sufism/hikam.md'
      - 'Lantern of the Path': 'books/sufism/lantern-path.md'
  - Practices and Teachings:
      - 'Introduction': 'books/practices-teachings/index.md'
      - 'Ripples of Light': 'books/practices-teachings/ripples-light.md'
      - 'Pointers to Presence': 'books/practices-teachings/pointers-presence.md'
      - 'Journey of the Self': 'books/practices-teachings/journey-self.md'
      - 'Happiness in Life and After Death': 'books/practices-teachings/happiness-life-death.md'
      - 'Calling Allah By His Most Beautiful Names': 'books/practices-teachings/calling-allah-beautiful-names.md'
      - 'The Hikam - The Wisdom of Ibn `Ata’ Allah': 'books/practices-teachings/hikam.md'
      - 'Lantern of the Path': 'books/practices-teachings/lantern-path.md'
      - '101 Helpful Illusions': 'books/practices-teachings/101-helpful-illusions.md'
      - 'Look Again': 'books/practices-teachings/look-again.md'
  - Talks, Interviews, and Courses:
      - 'Introduction': 'books/talks-interviews-courses/index.md'
      - 'Friday Discourses': 'books/talks-interviews-courses/friday-discourses.md'
      - 'Refinement of Character: Friday Discourses': 'books/talks-interviews-courses/refinement-character.md'
      - 'Journey of the Self': 'books/talks-interviews-courses/journey-self.md'
  - Poetry & Aphorisms:
      - 'Introduction': 'books/poetry-aphorisms/index.md'
  - Biography:
      - 'Introduction': 'books/biography/index.md'
      - 'Son of Karbala - The Spiritual Journey of an Iraqi Muslim': 'books/biography/son-karbala.md'
- Videos:
  - 'Overview': 'videos/index.md'
  - Introduction: 'videos/introduction.md'
  - Recommended: 'videos/recommended.md'
  - Conferences:
    - '2018 - What Are We Seeking?': 'videos/conferences/2018.md'
    - '2019 - The Human Quest': 'videos/conferences/2019.md'
    - '2020 - Reflections and Actions': 'videos/conferences/2020.md'
  - Qur’anic Commentary:
    - 'Human Duty and Destiny': 'videos/quran/duty-destiny.md'
    - 'Qur’an and Happiness': 'videos/quran/quran-happiness.md'
    - 'From Darkness to Light': 'videos/quran/darkness-to-light.md'
    - 'Surat al-Hadid': 'videos/quran/al-hadid.md'
    - 'Sacred Expressions in the Qur’an': 'videos/quran/sacred-expressions.md'
    - 'Prescriptions for Living': 'videos/quran/prescriptions-for-living.md'
  - Conversations:
      - 'Highwood': 'videos/conversations/highwood.md'
      - 'Ultimate Contentment': 'videos/conversations/ultimate-contentment.md'
      - 'Collected Talks': 'videos/conversations/collected.md'
      - 'Shaykh Muslim': 'videos/conversations/shaykh-muslim.md'  
- Articles:
  - 'Overview': 'articles/index.md'
  - 'Dhikr, Fikr, Himmah': 'articles/dhikr-fikr-himmah.md'
  - 'Less is More': 'articles/less-is-more.md'
  - 'Pointers to Haqq': 'articles/pointers-to-haqq.md'
  - 'Eid - The Return': 'articles/eid.md'
  - 'Natural Illusions': 'articles/natural-illusions.md'
  - 'Decree, Destiny and Enlightenment': 'articles/decree-destiny-enlightenment.md'
  - 'The Thread of Truth': 'articles/thread-of-truth.md'
  - 'Sufism and the Sufi': 'articles/sufism-sufi.md'
  - 'The Shock of Awakening': 'articles/shock-awakening.md'
  - 'To Be Alive': 'articles/to-be-alive.md'
  - 'The Parable of the Spider’s House': 'articles/parable-spider.md' 
  - 'The Journey of Transformation': 'articles/journey-transformation.md'
- ASK:
  - 'Academy of Self Knowledge': 'a-s-k/ask.md'
  - Cosmology of the Self:
    - 'Who am I?': 'a-s-k/cosmology-self/index.md'
    - Course Outline:
      - 'Early Childhood': 'a-s-k/cosmology-self/childhood.md'
      - 'Ethics & Character Traits': 'a-s-k/cosmology-self/ethics-character-traits.md'
      - 'Body-Mind-Spirit': 'a-s-k/cosmology-self/body-mind-spirit.md'
  - The Prophetic Way of Life:
    - 'Timeless Wisdom and the Modern World': 'a-s-k/prophetic-way/index.md'
    - Course Outline:
      - 'Conscious Worship': 'a-s-k/prophetic-way/conscious-worship.md'
      - 'Evolving Relationships': 'a-s-k/prophetic-way/evolving-relationships.md'
      - 'Guidance from Allah': 'a-s-k/prophetic-way/guidance-allah.md'
- Poetry:
  - 'Overview': 'poetry/index.md'
  - 'What Is It?': 'poetry/what-is-it.md'
  - 'The First Journey': 'poetry/first-journey.md'
  - 'Morning in the Plantation': 'poetry/morning-plantation.md'
  - 'Step With Caution': 'poetry/step-caution.md'
  - 'Binary Experience': 'poetry/binary-experience.md'
  - 'Human Modesty': 'poetry/human-modesty.md'
  - 'Perpetual': 'poetry/perpetual.md'
  - 'Big Questions': 'poetry/big-questions.md'
  - 'The Candle': 'poetry/the-candle.md'
  - 'Gravity': 'poetry/gravity.md'
  - 'Troubles': 'poetry/troubles.md'
  - 'The Passage of Time': 'poetry/passage-time.md'
  - 'Sleepwalking': 'poetry/sleepwalking.md'
  - 'One Face': 'poetry/one-face.md'
  - 'Enlightened Teachers': 'poetry/enlightened-teachers.md'
  - 'Fate': 'poetry/fate.md'
  - 'To Remember You Must Forget': 'poetry/remember-forget.md'
  - 'This City Has No Roads': 'poetry/city-no-roads.md'
- Aphorisms:
  - 'Aphorisms': 'aphorisms/index.md'
- Guides:
  - 'Overview': 'guides/index.md'
  - 'The Practice of Stillness': 'guides/practice-stillness.md'
  - 'The Self and its Journeys': 'guides/7-stations-4-journeys.md'
  - 'Fasting': 'guides/fasting.md'
  - 'Pilgrimage': 'guides/pilgrimage.md'
- Glossary:
  - 'Arabic Terms': 'glossary/index.md'
  - 'Key Words': 'glossary/key-words.md'
  - 'Journey Words': 'glossary/journey-words.md' 
  - Sideways Dictionary:
    - 'What is the sideways dictionary?': 'glossary/sideways-dictionary/what-is-the-sideways-dictionary.md'

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
