# Project information
site_name: SFH Foundation
site_description: Self, Soul, and Joyful Surrender
site_url: https://sfh-foundation.github.io/sfhfoundation/site/
site_dir: public/knowledge
logo_nav: https://sfh-foundation.github.io/sfhfoundation/

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: orange
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: 'sfh_logo.png'

extra_css: [extra.css]

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/SFH-Foundation/sfhfoundation'
    - type: 'twitter'
      link: 'https://twitter.com/cryptowanderer'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.extra

# Page tree
nav:
- Landing Page: '../'
- Newsletter: 'https://sfhfoundation.substack.com/'
- Books:
  - 'Overview': 'books/index.md'
  - General on Islam: 
      - 'Introduction': 'books/general-islam/index.md'
      - 'Transformative Worship in Islam': 'books/general-islam/transformative-worship.md'
      - 'The Thoughtful Guide to Islam': 'books/general-islam/thoughtful-guide-islam.md'
      - 'Elements of Islam': 'books/general-islam/elements-islam.md'
      - 'Sayings of the Prophet Muhammad': 'books/general-islam/sayings-muhammad.md'
      - 'Prophetic Traditions in Islam': 'books/general-islam/prophetic-traditions.md'
      - 'Living Islam - East & West': 'books/general-islam/living-islam.md'
      - Health Sciences - Early Islam:
        - 'Volume 1': 'books/general-islam/health-sciences/index.md'
        - 'Volume 2': 'books/general-islam/health-sciences/volume-2.md'
  - The Qur’an:
      - 'Introduction': 'books/quran/index.md'
      - 'Qur’an: 50 Vital Verses': 'books/quran/50-vital-verses.md'
      - Keys to the Qur’an:
        - 'Collected Volume': 'books/quran/keys/index.md'
        - 'Surah Fatiha & Baqarah': 'books/quran/keys/keys-1.md'
        - 'Surat Al-`Imran': 'books/quran/keys/keys-2.md'
        - 'Surat Yasin': 'books/quran/keys/keys-3.md'
        - 'Surah Ankabut, Al-Rahman, Al-Waqi`ah and Al-Mulk': 'books/quran/keys/keys-4.md'
        - 'The Juz Amma': 'books/quran/keys/keys-5.md'
      - 'The Story of Creation in the Qur’an': 'books/quran/story-creation-quran.md'
      - 'The Mercy of the Qur’an and The Advent of Zaman': 'books/quran/mercy-quran-advent-zaman.md'
      - 'The Essential Message Of the Qur’an': 'books/quran/essential-quran.md'
      - 'Sacred Alchemy: A Collection of Qur’anic Verses': 'books/quran/sacred-alchemy.md'
      - 'Qur’an’s Prescription for Life': 'books/quran/quran-prescriptions.md'
      - 'The Qur’an in Islam': 'books/quran/quran-islam.md'
  - Sufism and Self-Knowledge: 
      - 'Introduction': 'books/sufism/index.md'
      - 'Elements of Sufism': 'books/sufism/elements-sufism.md'
      - 'Spectrum of Reality: Sufi Insights': 'books/sufism/spectrum-reality.md'
      - 'The Sufi Way of Self-Enfoldment': 'books/sufism/sufi-self-enfoldment.md'
      - 'Witnessing Perfection: A Sufi Guide': 'books/sufism/witnessing-perfection.md'
      - 'Lantern of the Path': 'books/sufism/lantern-path.md'
      - 'Beginning’s End': 'books/sufism/beginnings-end.md'
      - 'Leaves From A Sufi Journal': 'books/sufism/leaves-sufi-journal.md'
  - Practices and Teachings:
      - 'Introduction': 'books/practices-teachings/index.md'
      - 'Transformative Worship In Islam': 'books/practices-teachings/transformative-worship.md'
      - 'Spectrum of Reality: Sufi Insights': 'books/practices-teachings/spectrum-reality.md'
      - 'Journey of the Self': 'books/practices-teachings/journey-self.md'
      - 'Happiness in Life and After Death': 'books/practices-teachings/happiness-life-death.md'
      - 'Decree and Destiny': 'books/practices-teachings/decree-destiny.md'
      - 'Calling Allah By His Most Beautiful Names': 'books/practices-teachings/calling-allah-beautiful-names.md'
      - 'Lantern of the Path': 'books/practices-teachings/lantern-path.md'
      - 'The Hikam': 'books/practices-teachings/hikam.md'
      - '101 Helpful Illusions': 'books/practices-teachings/101-helpful-illusions.md'
      - 'The Sayings & Wisdom of Imam `Ali': 'books/practices-teachings/sayings-imam-ali.md'
      - 'Cosmology Of The Self': 'books/practices-teachings/cosmology-self.md'
  - Talks, Interviews, and Courses:
      - 'Introduction': 'books/talks-interviews-courses/index.md'
      - 'Friday Discourses': 'books/talks-interviews-courses/friday-discourses.md'
      - 'Refinement of Character: Friday Discourses': 'books/talks-interviews-courses/refinement-character.md'
      - 'Journey of the Self': 'books/talks-interviews-courses/journey-self.md'
      - 'The Spiritual Path': 'books/talks-interviews-courses/spiritual-path.md'
      - 'ASK Course 1 - A Sufi Map of Self': 'books/talks-interviews-courses/ask-1-sufi-map-self.md'
      - 'ASK Course 2 - A Prophetic Way of Life': 'books/talks-interviews-courses/ask-2-prophetic-way-life.md'
      - 'The Connection Between the Absolute and the Relative': 'books/talks-interviews-courses/connection-absolute-relative.md'
  - Poetry & Aphorisms:
      - 'Introduction': 'books/poetry-aphorisms/index.md'
      - 'Ripples of Light': 'books/poetry-aphorisms/ripples-light.md'
      - 'Pointers to Presence': 'books/poetry-aphorisms/pointers-presence.md'
      - 'Look Again': 'books/poetry-aphorisms/look-again.md'
      - 'The Garden of Meaning': 'books/poetry-aphorisms/garden-meaning.md'
      - 'The Hikam - The Wisdom of Ibn `Ata’ Allah': 'books/poetry-aphorisms/hikam.md'
      - '101 Helpful Illusions': 'books/poetry-aphorisms/101-helpful-illusions.md'
      - 'Bursts of Silence': 'books/poetry-aphorisms/bursts-of-silence.md'
      - 'Sound Waves': 'books/poetry-aphorisms/sound-waves.md'
      - 'Beyond Windows': 'books/poetry-aphorisms/beyond-windows.md'
  - Biography:
      - 'Introduction': 'books/biography/index.md'
      - 'Son of Karbala': 'books/biography/son-karbala.md'
      - 'Sufi Encounters': 'books/biography/sufi-encounters.md'
- Videos:
  - 'Overview': 'videos/index.md'
  - Beginning: 'videos/beginning.md'
  - Learning: 'videos/learning.md'
  - Polishing: 'videos/polishing.md'
  - Qur’an:
    - 'Human Duty and Destiny': 'videos/quran/duty-destiny.md'
    - 'Qur’an and Happiness': 'videos/quran/quran-happiness.md'
    - 'From Darkness to Light': 'videos/quran/darkness-to-light.md'
    - 'Sacred Expressions': 'videos/quran/sacred-expressions.md'
    - 'Prescriptions for Living': 'videos/quran/prescriptions-for-living.md'
    - 'Surat al-Hadid': 'videos/quran/al-Hadid.md'
    - 'Surat al-Balad': 'videos/quran/al-Balad.md'
  - ASK:
    - '2012': 'videos/ask/2012.md'
    - '2013': 'videos/ask/2013.md'
  - Conferences:
    - '2018 - What Are We Seeking?': 'videos/conferences/2018.md'
    - '2019 - The Human Quest': 'videos/conferences/2019.md'
    - '2020 - Reflections and Actions': 'videos/conferences/2020.md'
  - Conversations:
      - 'Highwood': 'videos/conversations/highwood.md'
      - 'Ultimate Contentment': 'videos/conversations/ultimate-contentment.md'
      - 'Collected Interactions': 'videos/conversations/collected.md'
- Audios:
  - 'Most Recent': 'audios/index.md'
  - 'Guide to Listening': 'audios/guide.md'
  - 'Single Talks': 'audios/single-talks.md'
  - Series:
    - 'Enlightenment': 'audios/series/enlightenment.md'
    - 'Refinement of Character': 'audios/series/refinement-character.md'
    - 'Descriptive, Prescriptive Qur’an': 'audios/series/descriptive-prescriptive-quran.md'
    - 'Enhancing Human Experience': 'audios/series/practice-enhance-experience.md'
    - 'Islam and the Environment': 'audios/series/islam-environment.md'
    - 'Abstention, Fasting, Conduct': 'audios/series/abstention-fasting.md'
    - 'Qur’an Direct': 'audios/series/quran-direct.md'    
- Articles:
  - 'Overview': 'articles/index.md'
  - 'Dhikr, Fikr, Himmah': 'articles/dhikr-fikr-himmah.md'
  - 'Less is More': 'articles/less-is-more.md'
  - 'Pointers to Haqq': 'articles/pointers-to-haqq.md'
  - 'Eid - The Return': 'articles/eid.md'
  - 'Natural Illusions': 'articles/natural-illusions.md'
  - 'Decree, Destiny and Enlightenment': 'articles/decree-destiny-enlightenment.md'
  - 'The Thread of Truth': 'articles/thread-of-truth.md'
  - 'Sufism and the Sufi': 'articles/sufism-sufi.md'
  - 'The Shock of Awakening': 'articles/shock-awakening.md'
  - 'To Be Alive': 'articles/to-be-alive.md'
  - 'The Cycles of Life and Reality': 'articles/cycles-life-reality.md'
  - 'Consciousness': 'articles/consciousness.md'
  - 'The Parable of the Spider’s House': 'articles/parable-spider.md' 
  - 'The Journey of Transformation': 'articles/journey-transformation.md'
- Guides:
  - 'Overview': 'guides/index.md'
  - Practices: 
    - 'Meditation': 'guides/practice/meditation.md'
    - 'Supplication': 'guides/practice/supplication.md'
    - 'Stillness': 'guides/practice/stillness.md'
    - 'Transformative Worship': 'guides/practice/transformative-worship.md'
    - 'Witnessing Perfection': 'guides/practice/witnessing-perfection.md'
  - 'Maps & Models of the Self': 'guides/7-stations-4-journeys.md'
  - 'Virtuous Being, Higher Conduct': 'guides/virtue-higher-conduct.md'
  - 'Self Knowledge and Presence': 'guides/self-knowledge-presence.md'
  - Fasting: 
    - 'Fasting in History': 'guides/fasting/history.md'
    - 'The Islamic Fast': 'guides/fasting/islamic.md'
    - 'Meaning and Benefits': 'guides/fasting/meaning-benefits.md'
    - 'Outward Abstention': 'guides/fasting/outward-abstention.md'
    - 'Inward Abstention': 'guides/fasting/inward-abstention.md'
    - 'The Awakened Seeker': 'guides/fasting/awakened-seeker.md'
    - 'Feast of Fast-Breaking': 'guides/fasting/feast-fast-breaking.md'
  - 'Pilgrimage': 'guides/pilgrimage.md'
- ASK:
  - 'Academy of Self Knowledge': 'a-s-k/ask.md'
  - Cosmology of the Self:
    - 'Who am I?': 'a-s-k/cosmology-self/index.md'
    - Course Outline:
      - 'Early Childhood': 'a-s-k/cosmology-self/childhood.md'
      - 'Ethics & Character Traits': 'a-s-k/cosmology-self/ethics-character-traits.md'
      - 'Body-Mind-Spirit': 'a-s-k/cosmology-self/body-mind-spirit.md'
  - The Prophetic Way of Life:
    - 'Timeless Wisdom and the Modern World': 'a-s-k/prophetic-way/index.md'
    - Course Outline:
      - 'Conscious Worship': 'a-s-k/prophetic-way/conscious-worship.md'
      - 'Evolving Relationships': 'a-s-k/prophetic-way/evolving-relationships.md'
      - 'Guidance from Allah': 'a-s-k/prophetic-way/guidance-allah.md'
- Poetry:
  - 'Overview': 'poetry/index.md'
  - 'What Is It?': 'poetry/what-is-it.md'
  - 'The First Journey': 'poetry/first-journey.md'
  - 'Morning in the Plantation': 'poetry/morning-plantation.md'
  - 'Step With Caution': 'poetry/step-caution.md'
  - 'Binary Experience': 'poetry/binary-experience.md'
  - 'Human Modesty': 'poetry/human-modesty.md'
  - 'Perpetual': 'poetry/perpetual.md'
  - 'Big Questions': 'poetry/big-questions.md'
  - 'The Candle': 'poetry/the-candle.md'
  - 'Gravity': 'poetry/gravity.md'
  - 'Troubles': 'poetry/troubles.md'
  - 'The Passage of Time': 'poetry/passage-time.md'
  - 'Sleepwalking': 'poetry/sleepwalking.md'
  - 'One Face': 'poetry/one-face.md'
  - 'Enlightened Teachers': 'poetry/enlightened-teachers.md'
  - 'Fate': 'poetry/fate.md'
  - 'To Remember You Must Forget': 'poetry/remember-forget.md'
  - 'This City Has No Roads': 'poetry/city-no-roads.md'
- Aphorisms:
  - 'Aphorisms': 'aphorisms/index.md'
  - A Spectrum of Journeys: 
    - '1 - Nature, Desire, Harmony': 'aphorisms/spectrum/index.md'
    - '2 - Duality': 'aphorisms/spectrum/duality.md'
    - '3 - Guidance & Excellence': 'aphorisms/spectrum/guidance.md'
    - '4 - Victory & Gatheredness': 'aphorisms/spectrum/victory-gatheredness.md'
    - '5 - Wealth, Beauty, & Treasure': 'aphorisms/spectrum/wealth-beauty-treasure.md'
    - '6 - Trust & Presence': 'aphorisms/spectrum/trust-presence.md'
    - '7 - Heart': 'aphorisms/spectrum/heart.md'
    - '8 - Soul': 'aphorisms/spectrum/soul.md'
    - '9 - Truth & Light': 'aphorisms/spectrum/truth-light.md'
    - '10 - Differentiated Sameness': 'aphorisms/spectrum/differentiated-sameness.md'
    - '11 - Balance': 'aphorisms/spectrum/balance.md'
    - '12 - Service': 'aphorisms/spectrum/service.md'
    - '13 - Awakening': 'aphorisms/spectrum/awakening.md'
    - '14 - Purpose': 'aphorisms/spectrum/purpose.md'
    - '15 - Happiness & Content': 'aphorisms/spectrum/happiness-content.md'
- Glossary:
  - 'Arabic Terms': 'glossary/index.md'
  - 'Key Words': 'glossary/key-words.md'
  - 'Journey Words': 'glossary/journey-words.md' 
  - Sideways Dictionary:
    - 'What is the sideways dictionary?': 'glossary/sideways-dictionary/what-is-the-sideways-dictionary.md'

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
