# Project information
site_name: SFH Foundation
site_description: Self, soul, and joyful surrender

# Specific to set up
site_url: https://sfhfoundation.com/
site_dir: public

# Repository
repo_name: sfhfoundation
repo_url: https://github.com/SFH-Foundation/sfhfoundation
edit_uri: ""

extra_css: [extra.css]

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
  palette:
    primary: orange
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'logo.png'
  favicon: assets/images/favicon.ico

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: 'facebook'
      link: 'https://www.facebook.com/sfhfoundation/'
    - type: 'twitter'
      link: 'https://twitter.com/SFH_Foundation'
    - type: 'github'
      link: 'https://github.com/SFH-Foundation/sfhfoundation'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: andytudhope
      repo: africa
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra
  

# Page tree
nav:
  - Home: index.md
  - Welcome:
    - About: 'about.md'
    - Hope and Duty: 'hope.md'
    - Infinite and Eternal: 'infinite-eternal.md'
  - Gatherings:
    - 'Events': 'gatherings/index.md'
    - Past Events: 
      - 2020: 
        - 'Reflection & Action': 'gatherings/past/2020/reflection-action.md'
      - 2021:
        - 'Deep Time & Fulfilment': 'gatherings/past/2021/deep-time.md'
        - 'Two Friends': 'gatherings/past/2021/two-friends.md'
        - 'Inner Satisfaction, Outer Peace': 'gatherings/past/2021/inner-satisfaction-outer-peace.md'
        - 'Human Creation': 'gatherings/past/2021/human-creation.md'
        - 'Human Crisis': 'gatherings/past/2021/human-crisis.md'
        - 'Quran, Faith, Life': 'gatherings/past/2021/quran-faith-life.md'
        - 'Humanity in Unity': 'gatherings/past/2021/humanity-unity.md'
        - 'Experiencing Death Confirms Eternal Life': 'gatherings/past/2021/death-eternal-life.md'
        - 'Living Transcendence': 'gatherings/past/2021/living-transcendence.md'
        - 'Hope - Elixir to the Eternal': 'gatherings/past/2021/hope-elixir.md'
        - 'Fasting Part 1': 'gatherings/past/2021/fasting-1.md'
        - 'Individual & Community': 'gatherings/past/2021/individual-community.md'
        - 'Fasting Part 2': 'gatherings/past/2021/fasting-2.md'
        - 'Buddha at the Gas Pump': 'gatherings/past/2021/batgap.md'
        - 'Fasting Part 3': 'gatherings/past/2021/fasting-3.md'
        - 'Fasting Part 4': 'gatherings/past/2021/fasting-4.md'
        - 'Eid ul Fitr': 'gatherings/past/2021/eid-ul-fitr.md'
        - 'Universal Quran': 'gatherings/past/2021/universal-quran.md'
        - 'When Two Oceans Meet': 'gatherings/past/2021/two-oceans-meet.md'
        - 'The Tripod': 'gatherings/past/2021/the-tripod.md'
        - 'Celebrating the Eternal': 'gatherings/past/2021/celebrating-eternal.md'
        - 'Calibrating Muslim Mental Health': 'gatherings/past/2021/mental-health.md'
    - Messages:
      - 'COVID-19': 'gatherings/messages/index.md'
  - Videos:
    - Videos: 'videos/index.md'
    - Start Now: 'videos/start-now.md'
    - Pathways: 'videos/pathways.md'
    - Reflect: 'videos/reflect.md'
    - Review: 'videos/review.md'
    - Uncommon Dialogues: 'videos/uncommon-dialogues.md'
    - Qur’an:
      - 'The Universal Message': 'videos/quran/universal-message.md'
      - 'Human Duty and Destiny': 'videos/quran/duty-destiny.md'
      - 'Qur’an and Happiness': 'videos/quran/quran-happiness.md'
      - 'The Verse of Light': 'videos/quran/verse-of-light.md'
      - 'Surat al-Hadid': 'videos/quran/al-Hadid.md'
      - 'Fasting & Ramadan': 'videos/quran/fasting-ramadan.md'
    - Conferences:
      - '2013 - Celebrating The Universal Message of the Qur’an': 'videos/conferences/2013.md'
      - '2017 - From Darkness to Light': 'videos/conferences/2017.md'
      - '2018 - What Are We Seeking?': 'videos/conferences/2018.md'
      - '2019 - The Human Quest': 'videos/conferences/2019.md'
      - '2020 - Reflections and Actions': 'videos/conferences/2020.md'
    - Conversations:
        - 'Highwood': 'videos/conversations/highwood.md'
        - 'Presents': 'videos/conversations/collected.md'
        - 'Ultimate Contentment': 'videos/conversations/ultimate-contentment.md'
  - Audios:
    - 'Guide': 'audios/index.md'
    - 'Selected Talks': 'audios/selected-talks.md'
    - Series:
      - 'Gateways': 'audios/series/gateways-to-enlightenment.md'
      - Self Knowledge:
        - 'Listen': 'audios/series/self-knowledge.md'
        - Transcripts:
          - 'Changing You': 'audios/series/transcripts/sk1.md'
          - 'Light and Shadows': 'audios/series/transcripts/sk2.md'
          - 'The Soul': 'audios/series/transcripts/sk3.md'
          - 'The Map': 'audios/series/transcripts/sk4.md'
          - 'Conducting the Ultimate Quest': 'audios/series/transcripts/sk5.md'
      - 'Qur’an': 'audios/series/descriptive-prescriptive-quran.md'
  - Pointers:
    - A Spectrum of Journeys: 'pointers/index.md'
    - Duality:
      - 'Two Zones': 'pointers/spectrum/index.md'
      - 'Evolutionary Drives': 'pointers/spectrum/evolutionary-drives.md'
      - 'Revolutionary Drives': 'pointers/spectrum/revolutionary-drives.md'
      - 'Infinite Limits': 'pointers/spectrum/duality.md'
    - Humanity:
      - 'Life': 'pointers/spectrum/life.md'
      - 'Life Continued': 'pointers/spectrum/life-continued.md'
      - 'The Three C’s': 'pointers/spectrum/three-cs.md'
      - 'Drive for Excellence': 'pointers/spectrum/drive-for-excellence.md'
      - 'Destiny': 'pointers/spectrum/destiny.md'
    - Always Together:
      - 'Uncertain Confidence': 'pointers/spectrum/uncertain-confidence.md'
      - 'Nature, Desire, Harmony': 'pointers/spectrum/nature-desire-harmony.md'
      - 'Differentiated Sameness': 'pointers/spectrum/differentiated-sameness.md'
      - 'Service': 'pointers/spectrum/service.md'
      - 'Victory & Gatheredness': 'pointers/spectrum/victory-oneness.md'
    - Waking Up:
      - 'Trust & Presence': 'pointers/spectrum/trust-presence.md'
      - 'Boundless Wealth': 'pointers/spectrum/boundless-wealth.md'
      - 'Awakening': 'pointers/spectrum/awakening.md'
      - 'Purpose': 'pointers/spectrum/purpose.md'
    - The Light of Truth:
      - 'Heart': 'pointers/spectrum/heart.md'
      - 'Soul': 'pointers/spectrum/soul.md'
      - 'Truth & Light': 'pointers/spectrum/truth-light.md'
      - 'Wisdom': 'pointers/spectrum/wisdom.md'
    - Durable Contentment:
      - 'Inner Compass': 'pointers/spectrum/inner-compass.md'
      - 'Lasting Happiness': 'pointers/spectrum/happiness.md'
      - 'Balance': 'pointers/spectrum/balance.md'
      - 'Reality': 'pointers/spectrum/reality.md'
  - Poetry:
    - Overview: poetry/index.md
    - Beginning’s End: 
      - 'What Is It?': 'poetry/beginnings-end/what-is-it.md'
      - 'The First Journey': 'poetry/beginnings-end/first-journey.md'
      - 'Step With Caution': 'poetry/beginnings-end/step-caution.md'
      - 'Binary Experience': 'poetry/beginnings-end/binary-experience.md'
      - 'Human Modesty': 'poetry/beginnings-end/human-modesty.md'
      - 'Perpetual': 'poetry/beginnings-end/perpetual.md'
      - 'Big Questions': 'poetry/beginnings-end/big-questions.md'
      - 'The Candle': 'poetry/beginnings-end/the-candle.md'
      - 'Gravity': 'poetry/beginnings-end/gravity.md'
      - 'Troubles': 'poetry/beginnings-end/troubles.md'
      - 'The Passage of Time': 'poetry/beginnings-end/passage-time.md'
      - 'Sleepwalking': 'poetry/beginnings-end/sleepwalking.md'
      - 'One Face': 'poetry/beginnings-end/one-face.md'
      - 'Enlightened Teachers': 'poetry/beginnings-end/enlightened-teachers.md'
      - 'Fate': 'poetry/beginnings-end/fate.md'
      - 'To Remember You Must Forget': 'poetry/beginnings-end/remember-forget.md'
      - 'This City Has No Roads': 'poetry/beginnings-end/city-no-roads.md'
    - Within Space and Time:
      - 'Constant Needs': 'poetry/within-space-time/constant-needs.md'
      - 'Remedy of Absence': 'poetry/within-space-time/remedy-of-absence.md'
      - 'Not Abandoned': 'poetry/within-space-time/not-abandoned.md'
      - 'Noisy Silence': 'poetry/within-space-time/noisy-silence.md'
      - 'Silent Conversation': 'poetry/within-space-time/silent-conversation.md'
      - 'Pseudo Confidence': 'poetry/within-space-time/pseudo-confidence.md'
      - 'Truth in Me': 'poetry/within-space-time/truth-in-me.md'
      - 'Unforgettable Truth': 'poetry/within-space-time/unforgettable-truth.md'
    - Between Finite and Infinite:
      - 'Differentiated Sameness': 'poetry/between-finite-infinite/differentiated-sameness.md'
      - 'In Perpetuity': 'poetry/between-finite-infinite/in-perpetuity.md'
      - 'The Hidden Gift of Loneliness': 'poetry/between-finite-infinite/hidden-gift-loneliness.md'
      - 'Accept and Flow': 'poetry/between-finite-infinite/accept-and-flow.md'
      - 'The Way Out': 'poetry/between-finite-infinite/the-way-out.md'
      - 'Disguised Sameness': 'poetry/between-finite-infinite/disguised-sameness.md'
      - 'Self Declaring': 'poetry/between-finite-infinite/self-declaring.md'
    - Timeless:
      - 'To Know Truth': 'poetry/timeless/to-know-truth.md'
      - 'Discovering Treasure': 'poetry/timeless/discovering-treasure.md'
      - 'Awe and More': 'poetry/timeless/awe-and-more.md'
      - 'One Author': 'poetry/timeless/one-author.md'
      - 'Perfect Time': 'poetry/timeless/perfect-time.md'
      - 'Perpetual Love': 'poetry/timeless/perpetual-love.md'
      - 'Truth of Now': 'poetry/timeless/truth-of-now.md'
  - Reflections:
    - 'Overview': 'reflections/index.md'
    - Practices: 
      - 'Start': 'reflections/practice/index.md'
      - 'Stillness': 'reflections/practice/stillness.md'
      - 'Meditation': 'reflections/practice/meditation.md'
      - 'Transformative Worship': 'reflections/practice/transformative-worship.md'
      - 'Witnessing Perfection': 'reflections/practice/witnessing-perfection.md'
      - 'Sohbet Etiquette': 'reflections/practice/sohbet.md'
      - Fasting:
        - 'Introduction': 'reflections/practice/fasting/index.md'
        - 'Part 2': 'reflections/practice/fasting/part-2.md'
        - 'Part 3': 'reflections/practice/fasting/part-3.md'
        - 'Part 4': 'reflections/practice/fasting/part-4.md'
    - 'What Is It?': 'reflections/what-is-it.md'
    - 'Maps & Models of Self': 'reflections/4-journeys.md'
    - 'Vices, Virtues and Appropriate Conduct': 'reflections/vice-virtue-appropriate-conduct.md'
    - 'Self Knowledge and Presence': 'reflections/self-knowledge-presence.md'
  - Articles:
    - 'Overview': 'articles/index.md'
    - 'Who Are You, Where Are You?': 'articles/who-are-you-where-are-you.md'
    - 'Balance': 'articles/balance.md'
    - 'Less is More': 'articles/less-is-more.md'
    - 'Pointers to Truth': 'articles/pointers-to-truth.md'
    - 'Natural Illusions': 'articles/natural-illusions.md'
    - 'The Thread of Truth': 'articles/thread-of-truth.md'
    - 'To Be Alive': 'articles/to-be-alive.md'
    - 'The Cycles of Life and Reality': 'articles/cycles-life-reality.md'
    - 'Consciousness': 'articles/consciousness.md'
    - 'Sufism and the Sufi': 'articles/sufism-sufi.md'
    - 'Remembrance, Discrimination, Yearning': 'articles/remembrance-discrimination-yearning.md'
    - 'The Shock of Awakening': 'articles/shock-awakening.md'
    - 'The Parable of the Spider’s House': 'articles/parable-spider.md' 
    - 'The Journey of Transformation': 'articles/journey-transformation.md'
    - 'Arc of Life': 'articles/arc-of-life.md'
    - 'Decree, Destiny and Enlightenment': 'articles/decree-destiny-enlightenment.md'
    - 'Eid - The Return': 'articles/eid.md'
    - 'Universality, Locality & The Human': 'articles/universality-locality-human.md'
  - Books:
    - Overview: 'books/index.md'
  - ASK:
    - 'Academy of Self Knowledge': 'ask/index.md'
    - Glossary:
      - 'Arabic Terms': 'glossary/index.md'
      - 'Key Words': 'glossary/key-words.md'
      - 'Journey Words': 'glossary/journey-words.md' 
    - Sideways Dictionary:
      - 'What is the sideways dictionary?': 'glossary/sideways-dictionary/what-is-the-sideways-dictionary.md'
  - Contact: 
    - 'Connect With Us': 'contact.md'